"""Upgrade existing durable records to lifecycle-aware recovery.

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # These guards also make this compatible with fresh databases created from
    # the final 0001 definition during development.
    op.execute(
        "ALTER TABLE factory_events ADD COLUMN IF NOT EXISTS event_stage VARCHAR"
    )
    op.execute(
        "ALTER TABLE factory_snapshots "
        "ADD COLUMN IF NOT EXISTS sequence BIGINT GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_factory_snapshots_sequence "
        "ON factory_snapshots (sequence)"
    )
    op.execute(
        "ALTER TABLE factory_snapshots DROP CONSTRAINT IF EXISTS "
        "factory_snapshots_factory_name_snapshot_hash_key"
    )
    op.execute(
        """
        UPDATE factory_events AS event
        SET event_stage = CASE
            WHEN event.simulation_hour > COALESCE(
                (
                    SELECT MAX(snapshot.simulation_hour)
                    FROM factory_snapshots AS snapshot
                    WHERE snapshot.factory_name = event.factory_name
                ),
                -1
            ) THEN 'scheduled'
            ELSE 'applied'
        END
        WHERE event_stage IS NULL
        """
    )
    op.execute("ALTER TABLE factory_events ALTER COLUMN event_stage SET NOT NULL")
    op.execute("DROP INDEX IF EXISTS ix_factory_events_event_stage")
    op.execute(
        "CREATE INDEX ix_factory_events_event_stage ON factory_events (event_stage)"
    )
    op.execute(
        "ALTER TABLE factory_events "
        "DROP CONSTRAINT IF EXISTS factory_events_factory_name_event_id_key"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'uq_factory_event_lifecycle'
            ) THEN
                ALTER TABLE factory_events
                ADD CONSTRAINT uq_factory_event_lifecycle
                UNIQUE (factory_name, event_id, event_stage);
            END IF;
        END $$
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE factory_events "
        "DROP CONSTRAINT IF EXISTS uq_factory_event_lifecycle"
    )
    op.execute("DROP INDEX IF EXISTS ix_factory_events_event_stage")
    op.execute("ALTER TABLE factory_events DROP COLUMN IF EXISTS event_stage")
    op.execute("DROP INDEX IF EXISTS ix_factory_snapshots_sequence")
    op.create_unique_constraint(
        "factory_events_factory_name_event_id_key",
        "factory_events",
        ["factory_name", "event_id"],
    )
