"""Deterministic scheduling policy used before invoking a solver."""

from __future__ import annotations

from dataclasses import dataclass

from backend.optimizer.models import (
    OptimizeRequest,
    ScheduleResult,
    ScheduleStatus,
    UnscheduledOrder,
)
from backend.optimizer.validator import validate_schedule
from backend.simulator.models import (
    Machine,
    MachineStatus,
    Order,
    Product,
    ProductionJob,
    ShipmentStatus,
    q,
)
from backend.simulator.state import FactoryState


@dataclass
class _MachinePlan:
    available_hour: float
    family: str | None


def build_baseline_schedule(
    state: FactoryState,
    request: OptimizeRequest | None = None,
) -> ScheduleResult:
    """Greedily build a deterministic, independently validated schedule."""
    options = request or OptimizeRequest()
    horizon_end = state.sim_hour + options.horizon_hours
    machine_plans = {
        machine.id: _MachinePlan(
            available_hour=_machine_available_hour(machine, state.sim_hour),
            family=machine.current_family,
        )
        for machine in state.machine_list()
        if _can_schedule(machine)
    }
    inventory = {
        component_id: item.available for component_id, item in state.inventory.items()
    }
    received_shipments: set[str] = set()
    jobs: list[ProductionJob] = []
    unscheduled: list[UnscheduledOrder] = []

    orders = sorted(
        state.open_orders(),
        key=lambda order: (order.priority, order.due_hour, order.id),
    )
    for order in orders:
        product = state.products.get(order.product_id)
        if product is None:
            unscheduled.append(_unscheduled(order, "unknown_product"))
            continue

        candidates = _candidate_machines(state, machine_plans, product)
        if not candidates:
            unscheduled.append(_unscheduled(order, "no_compatible_machine"))
            continue

        quantity = int(order.remaining)
        if quantity <= 0:
            continue

        machine, start_hour, _ = _choose_machine(
            candidates,
            machine_plans,
            product,
            quantity,
        )
        inventory_ready_hour = _inventory_ready_hour(
            state,
            product,
            quantity,
            start_hour,
            inventory,
            received_shipments,
        )
        if inventory_ready_hour is None:
            unscheduled.append(_unscheduled(order, "insufficient_inventory"))
            continue
        start_hour = inventory_ready_hour

        changeover = _changeover_hours(machine, machine_plans[machine.id], product)
        end_hour = q(start_hour + changeover + quantity / machine.capacity_per_hour)
        if end_hour > horizon_end:
            unscheduled.append(_unscheduled(order, "outside_horizon"))
            continue

        job = ProductionJob(
            id=f"job-{state.schedule_version + 1}-{len(jobs) + 1:04d}",
            order_id=order.id,
            machine_id=machine.id,
            product_id=product.id,
            start_hour=start_hour,
            end_hour=end_hour,
            quantity=quantity,
            schedule_version=state.schedule_version + 1,
        )
        jobs.append(job)
        _consume_inventory(product, quantity, inventory)
        machine_plans[machine.id] = _MachinePlan(end_hour, product.family)

    if not jobs and unscheduled:
        status = ScheduleStatus.INFEASIBLE
    elif unscheduled:
        status = ScheduleStatus.PARTIAL
    else:
        status = ScheduleStatus.FEASIBLE

    validation = validate_schedule(state, jobs)
    result = ScheduleResult(
        status=status,
        jobs=jobs,
        unscheduled_orders=unscheduled,
        validation=validation,
        notes=["Generated by the deterministic baseline scheduler."],
    )
    if not validation.is_valid:
        result.status = ScheduleStatus.ERROR
        result.notes.append("The generated candidate failed independent validation.")
    return result


def _can_schedule(machine: Machine) -> bool:
    return machine.status != MachineStatus.MAINTENANCE and not (
        machine.status == MachineStatus.DOWN and machine.down_until_hour is None
    )


def _machine_available_hour(machine: Machine, now: float) -> float:
    return max(now, machine.down_until_hour or now)


def _candidate_machines(
    state: FactoryState,
    plans: dict[str, _MachinePlan],
    product: Product,
) -> list[Machine]:
    return [
        state.machines[machine_id]
        for machine_id in sorted(plans)
        if state.machines[machine_id].can_produce(product.id)
        and state.machines[machine_id].capacity_per_hour > 0
    ]


def _choose_machine(
    machines: list[Machine],
    plans: dict[str, _MachinePlan],
    product: Product,
    quantity: int,
) -> tuple[Machine, float, float]:
    choices = []
    for machine in machines:
        plan = plans[machine.id]
        end = q(
            plan.available_hour
            + _changeover_hours(machine, plan, product)
            + quantity / machine.capacity_per_hour
        )
        choices.append((end, plan.available_hour, machine.id, machine))
    end, start, _, machine = min(choices, key=lambda choice: choice[:3])
    return machine, start, end


def _changeover_hours(
    machine: Machine,
    plan: _MachinePlan,
    product: Product,
) -> float:
    if plan.family == product.family:
        return 0.0
    return machine.changeover_minutes / 60


def _inventory_ready_hour(
    state: FactoryState,
    product: Product,
    quantity: int,
    earliest: float,
    inventory: dict[str, float],
    received_shipments: set[str],
) -> float | None:
    candidate_hours = [earliest]
    candidate_hours.extend(
        shipment.eta_hour
        for shipment in state.shipment_list()
        if shipment.status != ShipmentStatus.RECEIVED
        and shipment.id not in received_shipments
        and shipment.eta_hour >= earliest
    )

    for hour in sorted(set(candidate_hours)):
        for shipment in state.shipment_list():
            if (
                shipment.status != ShipmentStatus.RECEIVED
                and shipment.id not in received_shipments
                and shipment.eta_hour <= hour
            ):
                inventory[shipment.component_id] = (
                    inventory.get(shipment.component_id, 0) + shipment.quantity
                )
                received_shipments.add(shipment.id)

        if all(
            inventory.get(component_id, 0) >= amount * quantity
            for component_id, amount in product.bom.items()
        ):
            return q(hour)
    return None


def _consume_inventory(
    product: Product,
    quantity: int,
    inventory: dict[str, float],
) -> None:
    for component_id, amount in product.bom.items():
        inventory[component_id] -= amount * quantity


def _unscheduled(order: Order, reason: str) -> UnscheduledOrder:
    explanations = {
        "unknown_product": "The order references a product that does not exist.",
        "no_compatible_machine": "No available machine can produce this product.",
        "insufficient_inventory": "Required components are not available in time.",
        "outside_horizon": "The job cannot finish inside the planning horizon.",
    }
    return UnscheduledOrder(
        order_id=order.id,
        reason_code=reason,
        explanation=explanations[reason],
        required_action="Review capacity, inventory, or the planning horizon.",
    )
